using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PureFix.Types.Core
{
    public static class MsgType
    {
        /// <summary>
        /// Returns an interned string for known FIX message types, avoiding allocation.
        /// Falls back to creating a new string for unknown types.
        /// </summary>
        public static string Intern(ReadOnlySpan<byte> bytes)
        {
            return bytes.Length switch
            {
                1 => InternSingle(bytes[0]),
                2 => InternDouble(bytes[0], bytes[1]),
                _ => Encoding.ASCII.GetString(bytes) // Unknown - allocate
            };
        }

        private static string InternSingle(byte b) => b switch
        {
            (byte)'0' => Heartbeat,
            (byte)'1' => TestRequest,
            (byte)'2' => ResendRequest,
            (byte)'3' => Reject,
            (byte)'4' => SequenceReset,
            (byte)'5' => Logout,
            (byte)'6' => Ioi,
            (byte)'7' => Advertisement,
            (byte)'8' => ExecutionReport,
            (byte)'9' => OrderCancelReject,
            (byte)'A' => Logon,
            (byte)'B' => News,
            (byte)'C' => Email,
            (byte)'D' => NewOrderSingle,
            (byte)'E' => NewOrderList,
            (byte)'F' => OrderCancelRequest,
            (byte)'G' => OrderCancelReplaceRequest,
            (byte)'H' => OrderStatusRequest,
            (byte)'J' => AllocationInstruction,
            (byte)'K' => ListCancelRequest,
            (byte)'L' => ListExecute,
            (byte)'M' => ListStatusRequest,
            (byte)'N' => ListStatus,
            (byte)'P' => AllocationInstructionAck,
            (byte)'Q' => DontKnowTrade,
            (byte)'R' => QuoteRequest,
            (byte)'S' => Quote,
            (byte)'T' => SettlementInstructions,
            (byte)'V' => MarketDataRequest,
            (byte)'W' => MarketDataSnapshotFullRefresh,
            (byte)'X' => MarketDataIncrementalRefresh,
            (byte)'Y' => MarketDataRequestReject,
            (byte)'Z' => QuoteCancel,
            (byte)'a' => QuoteStatusRequest,
            (byte)'b' => MassQuoteAck,
            (byte)'c' => SecurityDefinitionRequest,
            (byte)'d' => SecurityDefinition,
            (byte)'e' => SecurityStatusRequest,
            (byte)'f' => SecurityStatus,
            (byte)'g' => TradingSessionStatusRequest,
            (byte)'h' => TradingSessionStatus,
            (byte)'i' => MassQuote,
            (byte)'j' => BusinessMessageReject,
            (byte)'k' => BidRequest,
            (byte)'l' => BidResponse,
            (byte)'m' => ListStrikePrice,
            (byte)'o' => RegistrationInstructions,
            (byte)'p' => RegistrationInstructionsResponse,
            (byte)'q' => OrderMassCancelRequest,
            (byte)'r' => OrderMassCancelReport,
            (byte)'s' => NewOrderCross,
            (byte)'t' => CrossOrderCancelReplaceRequest,
            (byte)'u' => CrossOrderCancelRequest,
            (byte)'v' => SecurityTypeRequest,
            (byte)'w' => SecurityTypes,
            (byte)'x' => SecurityListRequest,
            (byte)'y' => SecurityList,
            (byte)'z' => DerivativeSecurityListRequest,
            _ => ((char)b).ToString() // Unknown single char - allocate
        };

        private static string InternDouble(byte b0, byte b1) => (b0, b1) switch
        {
            ((byte)'A', (byte)'A') => DerivativeSecurityList,
            ((byte)'A', (byte)'B') => NewOrderMultileg,
            ((byte)'A', (byte)'C') => MultilegOrderCancelReplace,
            ((byte)'A', (byte)'D') => TradeCaptureReportRequest,
            ((byte)'A', (byte)'E') => TradeCaptureReport,
            ((byte)'A', (byte)'F') => OrderMassStatusRequest,
            ((byte)'A', (byte)'G') => QuoteRequestReject,
            ((byte)'A', (byte)'H') => RfqRequest,
            ((byte)'A', (byte)'I') => QuoteStatusReport,
            ((byte)'A', (byte)'J') => QuoteResponse,
            ((byte)'A', (byte)'K') => Confirmation,
            ((byte)'A', (byte)'L') => PositionMaintenanceRequest,
            ((byte)'A', (byte)'M') => PositionMaintenanceReport,
            ((byte)'A', (byte)'N') => RequestForPositions,
            ((byte)'A', (byte)'O') => RequestForPositionsAck,
            ((byte)'A', (byte)'P') => PositionReport,
            ((byte)'A', (byte)'Q') => TradeCaptureReportRequestAck,
            ((byte)'A', (byte)'R') => TradeCaptureReportAck,
            ((byte)'A', (byte)'S') => AllocationReport,
            ((byte)'A', (byte)'T') => AllocationReportAck,
            ((byte)'A', (byte)'U') => ConfirmationAck,
            ((byte)'A', (byte)'V') => SettlementInstructionRequest,
            ((byte)'A', (byte)'W') => AssignmentReport,
            ((byte)'A', (byte)'X') => CollateralRequest,
            ((byte)'A', (byte)'Y') => CollateralAssignment,
            ((byte)'A', (byte)'Z') => CollateralResponse,
            ((byte)'B', (byte)'A') => CollateralReport,
            ((byte)'B', (byte)'B') => CollateralInquiry,
            ((byte)'B', (byte)'C') => NetworkCounterpartySystemStatusRequest,
            ((byte)'B', (byte)'D') => NetworkCounterpartySystemStatusResponse,
            ((byte)'B', (byte)'E') => UserRequest,
            ((byte)'B', (byte)'F') => UserResponse,
            ((byte)'B', (byte)'G') => CollateralInquiryAck,
            ((byte)'B', (byte)'H') => ConfirmationRequest,
            ((byte)'B', (byte)'I') => TradingSessionListRequest,
            ((byte)'B', (byte)'J') => TradingSessionList,
            ((byte)'B', (byte)'K') => SecurityListUpdateReport,
            ((byte)'B', (byte)'L') => AdjustedPositionReport,
            ((byte)'B', (byte)'M') => AllocationInstructionAlert,
            ((byte)'B', (byte)'N') => ExecutionAck,
            ((byte)'B', (byte)'O') => ContraryIntentionReport,
            ((byte)'B', (byte)'P') => SecurityDefinitionUpdateReport,
            ((byte)'B', (byte)'Q') => SettlementObligationReport,
            ((byte)'B', (byte)'R') => DerivativeSecurityListUpdateReport,
            ((byte)'B', (byte)'S') => TradingSessionListUpdateReport,
            ((byte)'B', (byte)'T') => MarketDefinitionRequest,
            ((byte)'B', (byte)'U') => MarketDefinition,
            ((byte)'B', (byte)'V') => MarketDefinitionUpdateReport,
            ((byte)'B', (byte)'W') => ApplicationMessageRequest,
            ((byte)'B', (byte)'X') => ApplicationMessageRequestAck,
            ((byte)'B', (byte)'Y') => ApplicationMessageReport,
            ((byte)'B', (byte)'Z') => OrderMassActionReport,
            ((byte)'C', (byte)'A') => OrderMassActionRequest,
            ((byte)'C', (byte)'B') => UserNotification,
            ((byte)'C', (byte)'C') => StreamAssignmentRequest,
            ((byte)'C', (byte)'D') => StreamAssignmentReport,
            ((byte)'C', (byte)'E') => StreamAssignmentReportAck,
            ((byte)'C', (byte)'F') => PartyDetailsListRequest,
            ((byte)'C', (byte)'G') => PartyDetailsListReport,
            ((byte)'C', (byte)'H') => MarginRequirementInquiry,
            ((byte)'C', (byte)'I') => MarginRequirementInquiryAck,
            ((byte)'C', (byte)'J') => MarginRequirementReport,
            ((byte)'C', (byte)'K') => PartyDetailsListUpdateReport,
            ((byte)'C', (byte)'L') => PartyRiskLimitsRequest,
            ((byte)'C', (byte)'M') => PartyRiskLimitsReport,
            ((byte)'C', (byte)'N') => SecurityMassStatusRequest,
            ((byte)'C', (byte)'O') => SecurityMassStatus,
            ((byte)'C', (byte)'Q') => AccountSummaryReport,
            ((byte)'C', (byte)'R') => PartyRiskLimitsUpdateReport,
            ((byte)'C', (byte)'S') => PartyRiskLimitsDefinitionRequest,
            ((byte)'C', (byte)'T') => PartyRiskLimitsDefinitionRequestAck,
            ((byte)'C', (byte)'U') => PartyEntitlementsRequest,
            ((byte)'C', (byte)'V') => PartyEntitlementsReport,
            ((byte)'C', (byte)'W') => QuoteAck,
            ((byte)'C', (byte)'X') => PartyDetailsDefinitionRequest,
            ((byte)'C', (byte)'Y') => PartyDetailsDefinitionRequestAck,
            ((byte)'C', (byte)'Z') => PartyEntitlementsUpdateReport,
            ((byte)'D', (byte)'A') => PartyEntitlementsDefinitionRequest,
            ((byte)'D', (byte)'B') => PartyEntitlementsDefinitionRequestAck,
            ((byte)'D', (byte)'C') => TradeMatchReport,
            ((byte)'D', (byte)'D') => TradeMatchReportAck,
            ((byte)'D', (byte)'E') => PartyRiskLimitsReportAck,
            ((byte)'D', (byte)'F') => PartyRiskLimitCheckRequest,
            ((byte)'D', (byte)'G') => PartyRiskLimitCheckRequestAck,
            ((byte)'D', (byte)'H') => PartyActionRequest,
            ((byte)'D', (byte)'I') => PartyActionReport,
            ((byte)'D', (byte)'J') => MassOrder,
            ((byte)'D', (byte)'K') => MassOrderAck,
            ((byte)'D', (byte)'L') => PositionTransferInstruction,
            ((byte)'D', (byte)'M') => PositionTransferInstructionAck,
            ((byte)'D', (byte)'N') => PositionTransferReport,
            ((byte)'D', (byte)'O') => MarketDataStatisticsRequest,
            ((byte)'D', (byte)'P') => MarketDataStatisticsReport,
            ((byte)'D', (byte)'Q') => CollateralReportAck,
            ((byte)'D', (byte)'R') => MarketDataReport,
            ((byte)'D', (byte)'S') => CrossRequest,
            ((byte)'D', (byte)'T') => CrossRequestAck,
            ((byte)'D', (byte)'U') => AllocationInstructionAlertRequest,
            ((byte)'D', (byte)'V') => AllocationInstructionAlertRequestAck,
            ((byte)'D', (byte)'W') => TradeAggregationRequest,
            ((byte)'D', (byte)'X') => TradeAggregationReport,
            ((byte)'D', (byte)'Y') => PayManagementRequest,
            ((byte)'D', (byte)'Z') => PayManagementRequestAck,
            ((byte)'E', (byte)'A') => PayManagementReport,
            ((byte)'E', (byte)'B') => PayManagementReportAck,
            _ => Encoding.ASCII.GetString([(byte)b0, (byte)b1]) // Unknown - allocate
        };

        public const string Heartbeat = "0";
        public const string TestRequest = "1";
        public const string ResendRequest = "2";
        public const string Reject = "3";
        public const string SequenceReset = "4";
        public const string Logout = "5";
        public const string Ioi = "6";
        public const string Advertisement = "7";
        public const string ExecutionReport = "8";
        public const string OrderCancelReject = "9";
        public const string Logon = "A";
        public const string News = "B";
        public const string Email = "C";
        public const string NewOrderSingle = "D";
        public const string NewOrderList = "E";
        public const string OrderCancelRequest = "F";
        public const string OrderCancelReplaceRequest = "G";
        public const string OrderStatusRequest = "H";
        public const string AllocationInstruction = "J";
        public const string ListCancelRequest = "K";
        public const string ListExecute = "L";
        public const string ListStatusRequest = "M";
        public const string ListStatus = "N";
        public const string AllocationInstructionAck = "P";
        public const string DontKnowTrade = "Q";
        public const string QuoteRequest = "R";
        public const string Quote = "S";
        public const string SettlementInstructions = "T";
        public const string MarketDataRequest = "V";
        public const string MarketDataSnapshotFullRefresh = "W";
        public const string MarketDataIncrementalRefresh = "X";
        public const string MarketDataRequestReject = "Y";
        public const string QuoteCancel = "Z";
        public const string QuoteStatusRequest = "a";
        public const string MassQuoteAck = "b";
        public const string SecurityDefinitionRequest = "c";
        public const string SecurityDefinition = "d";
        public const string SecurityStatusRequest = "e";
        public const string SecurityStatus = "f";
        public const string TradingSessionStatusRequest = "g";
        public const string TradingSessionStatus = "h";
        public const string MassQuote = "i";
        public const string BusinessMessageReject = "j";
        public const string BidRequest = "k";
        public const string BidResponse = "l";
        public const string ListStrikePrice = "m";
        public const string RegistrationInstructions = "o";
        public const string RegistrationInstructionsResponse = "p";
        public const string OrderMassCancelRequest = "q";
        public const string OrderMassCancelReport = "r";
        public const string NewOrderCross = "s";
        public const string CrossOrderCancelReplaceRequest = "t";
        public const string CrossOrderCancelRequest = "u";
        public const string SecurityTypeRequest = "v";
        public const string SecurityTypes = "w";
        public const string SecurityListRequest = "x";
        public const string SecurityList = "y";
        public const string DerivativeSecurityListRequest = "z";
        public const string DerivativeSecurityList = "AA";
        public const string NewOrderMultileg = "AB";
        public const string MultilegOrderCancelReplace = "AC";
        public const string TradeCaptureReportRequest = "AD";
        public const string TradeCaptureReport = "AE";
        public const string OrderMassStatusRequest = "AF";
        public const string QuoteRequestReject = "AG";
        public const string RfqRequest = "AH";
        public const string QuoteStatusReport = "AI";
        public const string QuoteResponse = "AJ";
        public const string Confirmation = "AK";
        public const string PositionMaintenanceRequest = "AL";
        public const string PositionMaintenanceReport = "AM";
        public const string RequestForPositions = "AN";
        public const string RequestForPositionsAck = "AO";
        public const string PositionReport = "AP";
        public const string TradeCaptureReportRequestAck = "AQ";
        public const string TradeCaptureReportAck = "AR";
        public const string AllocationReport = "AS";
        public const string AllocationReportAck = "AT";
        public const string ConfirmationAck = "AU";
        public const string SettlementInstructionRequest = "AV";
        public const string AssignmentReport = "AW";
        public const string CollateralRequest = "AX";
        public const string CollateralAssignment = "AY";
        public const string CollateralResponse = "AZ";
        public const string CollateralReport = "BA";
        public const string CollateralInquiry = "BB";
        public const string NetworkCounterpartySystemStatusRequest = "BC";
        public const string NetworkCounterpartySystemStatusResponse = "BD";
        public const string UserRequest = "BE";
        public const string UserResponse = "BF";
        public const string CollateralInquiryAck = "BG";
        public const string ConfirmationRequest = "BH";
        public const string ContraryIntentionReport = "BO";
        public const string SecurityDefinitionUpdateReport = "BP";
        public const string SecurityListUpdateReport = "BK";
        public const string AdjustedPositionReport = "BL";
        public const string AllocationInstructionAlert = "BM";
        public const string ExecutionAck = "BN";
        public const string TradingSessionList = "BJ";
        public const string TradingSessionListRequest = "BI";
        public const string SettlementObligationReport = "BQ";
        public const string DerivativeSecurityListUpdateReport = "BR";
        public const string TradingSessionListUpdateReport = "BS";
        public const string MarketDefinitionRequest = "BT";
        public const string MarketDefinition = "BU";
        public const string MarketDefinitionUpdateReport = "BV";
        public const string ApplicationMessageRequest = "BW";
        public const string ApplicationMessageRequestAck = "BX";
        public const string ApplicationMessageReport = "BY";
        public const string OrderMassActionReport = "BZ";
        public const string OrderMassActionRequest = "CA";
        public const string UserNotification = "CB";
        public const string StreamAssignmentRequest = "CC";
        public const string StreamAssignmentReport = "CD";
        public const string StreamAssignmentReportAck = "CE";
        public const string PartyDetailsListRequest = "CF";
        public const string PartyDetailsListReport = "CG";
        public const string MarginRequirementInquiry = "CH";
        public const string MarginRequirementInquiryAck = "CI";
        public const string MarginRequirementReport = "CJ";
        public const string PartyDetailsListUpdateReport = "CK";
        public const string PartyRiskLimitsRequest = "CL";
        public const string PartyRiskLimitsReport = "CM";
        public const string SecurityMassStatusRequest = "CN";
        public const string SecurityMassStatus = "CO";
        public const string AccountSummaryReport = "CQ";
        public const string PartyRiskLimitsUpdateReport = "CR";
        public const string PartyRiskLimitsDefinitionRequest = "CS";
        public const string PartyRiskLimitsDefinitionRequestAck = "CT";
        public const string PartyEntitlementsRequest = "CU";
        public const string PartyEntitlementsReport = "CV";
        public const string QuoteAck = "CW";
        public const string PartyDetailsDefinitionRequest = "CX";
        public const string PartyDetailsDefinitionRequestAck = "CY";
        public const string PartyEntitlementsUpdateReport = "CZ";
        public const string PartyEntitlementsDefinitionRequest = "DA";
        public const string PartyEntitlementsDefinitionRequestAck = "DB";
        public const string TradeMatchReport = "DC";
        public const string TradeMatchReportAck = "DD";
        public const string PartyRiskLimitsReportAck = "DE";
        public const string PartyRiskLimitCheckRequest = "DF";
        public const string PartyRiskLimitCheckRequestAck = "DG";
        public const string PartyActionRequest = "DH";
        public const string PartyActionReport = "DI";
        public const string MassOrder = "DJ";
        public const string MassOrderAck = "DK";
        public const string PositionTransferInstruction = "DL";
        public const string PositionTransferInstructionAck = "DM";
        public const string PositionTransferReport = "DN";
        public const string MarketDataStatisticsRequest = "DO";
        public const string MarketDataStatisticsReport = "DP";
        public const string CollateralReportAck = "DQ";
        public const string MarketDataReport = "DR";
        public const string CrossRequest = "DS";
        public const string CrossRequestAck = "DT";
        public const string AllocationInstructionAlertRequest = "DU";
        public const string AllocationInstructionAlertRequestAck = "DV";
        public const string TradeAggregationRequest = "DW";
        public const string TradeAggregationReport = "DX";
        public const string PayManagementReport = "EA";
        public const string PayManagementReportAck = "EB";
        public const string PayManagementRequest = "DY";
        public const string PayManagementRequestAck = "DZ";
    }
}
